/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.shane;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ObxAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 9154735361424542180L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ObxAvroModel\",\"namespace\":\"com.shane\",\"fields\":[{\"name\":\"msh_ts\",\"type\":\"long\"},{\"name\":\"alarm_ts\",\"type\":\"long\"},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"unit\",\"type\":\"string\"},{\"name\":\"bed\",\"type\":\"string\"},{\"name\":\"channel\",\"type\":\"string\"},{\"name\":\"text\",\"type\":\"string\"}]}");
    public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
    @Deprecated public long msh_ts;
    @Deprecated public long alarm_ts;
    @Deprecated public java.lang.CharSequence source;
    @Deprecated public java.lang.CharSequence unit;
    @Deprecated public java.lang.CharSequence bed;
    @Deprecated public java.lang.CharSequence channel;
    @Deprecated public java.lang.CharSequence text;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public ObxAvroModel() {}

    /**
     * All-args constructor.
     * @param msh_ts The new value for msh_ts
     * @param alarm_ts The new value for alarm_ts
     * @param source The new value for source
     * @param unit The new value for unit
     * @param bed The new value for bed
     * @param channel The new value for channel
     * @param text The new value for text
     */
    public ObxAvroModel(java.lang.Long msh_ts, java.lang.Long alarm_ts, java.lang.CharSequence source, java.lang.CharSequence unit, java.lang.CharSequence bed, java.lang.CharSequence channel, java.lang.CharSequence text) {
        this.msh_ts = msh_ts;
        this.alarm_ts = alarm_ts;
        this.source = source;
        this.unit = unit;
        this.bed = bed;
        this.channel = channel;
        this.text = text;
    }

    public org.apache.avro.Schema getSchema() { return SCHEMA$; }
    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0: return msh_ts;
            case 1: return alarm_ts;
            case 2: return source;
            case 3: return unit;
            case 4: return bed;
            case 5: return channel;
            case 6: return text;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value="unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0: msh_ts = (java.lang.Long)value$; break;
            case 1: alarm_ts = (java.lang.Long)value$; break;
            case 2: source = (java.lang.CharSequence)value$; break;
            case 3: unit = (java.lang.CharSequence)value$; break;
            case 4: bed = (java.lang.CharSequence)value$; break;
            case 5: channel = (java.lang.CharSequence)value$; break;
            case 6: text = (java.lang.CharSequence)value$; break;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'msh_ts' field.
     * @return The value of the 'msh_ts' field.
     */
    public java.lang.Long getMshTs() {
        return msh_ts;
    }

    /**
     * Sets the value of the 'msh_ts' field.
     * @param value the value to set.
     */
    public void setMshTs(java.lang.Long value) {
        this.msh_ts = value;
    }

    /**
     * Gets the value of the 'alarm_ts' field.
     * @return The value of the 'alarm_ts' field.
     */
    public java.lang.Long getAlarmTs() {
        return alarm_ts;
    }

    /**
     * Sets the value of the 'alarm_ts' field.
     * @param value the value to set.
     */
    public void setAlarmTs(java.lang.Long value) {
        this.alarm_ts = value;
    }

    /**
     * Gets the value of the 'source' field.
     * @return The value of the 'source' field.
     */
    public java.lang.CharSequence getSource() {
        return source;
    }

    /**
     * Sets the value of the 'source' field.
     * @param value the value to set.
     */
    public void setSource(java.lang.CharSequence value) {
        this.source = value;
    }

    /**
     * Gets the value of the 'unit' field.
     * @return The value of the 'unit' field.
     */
    public java.lang.CharSequence getUnit() {
        return unit;
    }

    /**
     * Sets the value of the 'unit' field.
     * @param value the value to set.
     */
    public void setUnit(java.lang.CharSequence value) {
        this.unit = value;
    }

    /**
     * Gets the value of the 'bed' field.
     * @return The value of the 'bed' field.
     */
    public java.lang.CharSequence getBed() {
        return bed;
    }

    /**
     * Sets the value of the 'bed' field.
     * @param value the value to set.
     */
    public void setBed(java.lang.CharSequence value) {
        this.bed = value;
    }

    /**
     * Gets the value of the 'channel' field.
     * @return The value of the 'channel' field.
     */
    public java.lang.CharSequence getChannel() {
        return channel;
    }

    /**
     * Sets the value of the 'channel' field.
     * @param value the value to set.
     */
    public void setChannel(java.lang.CharSequence value) {
        this.channel = value;
    }

    /**
     * Gets the value of the 'text' field.
     * @return The value of the 'text' field.
     */
    public java.lang.CharSequence getText() {
        return text;
    }

    /**
     * Sets the value of the 'text' field.
     * @param value the value to set.
     */
    public void setText(java.lang.CharSequence value) {
        this.text = value;
    }

    /**
     * Creates a new ObxAvroModel RecordBuilder.
     * @return A new ObxAvroModel RecordBuilder
     */
    public static com.shane.ObxAvroModel.Builder newBuilder() {
        return new com.shane.ObxAvroModel.Builder();
    }

    /**
     * Creates a new ObxAvroModel RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new ObxAvroModel RecordBuilder
     */
    public static com.shane.ObxAvroModel.Builder newBuilder(com.shane.ObxAvroModel.Builder other) {
        return new com.shane.ObxAvroModel.Builder(other);
    }

    /**
     * Creates a new ObxAvroModel RecordBuilder by copying an existing ObxAvroModel instance.
     * @param other The existing instance to copy.
     * @return A new ObxAvroModel RecordBuilder
     */
    public static com.shane.ObxAvroModel.Builder newBuilder(com.shane.ObxAvroModel other) {
        return new com.shane.ObxAvroModel.Builder(other);
    }

    /**
     * RecordBuilder for ObxAvroModel instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ObxAvroModel>
            implements org.apache.avro.data.RecordBuilder<ObxAvroModel> {

        private long msh_ts;
        private long alarm_ts;
        private java.lang.CharSequence source;
        private java.lang.CharSequence unit;
        private java.lang.CharSequence bed;
        private java.lang.CharSequence channel;
        private java.lang.CharSequence text;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.shane.ObxAvroModel.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.msh_ts)) {
                this.msh_ts = data().deepCopy(fields()[0].schema(), other.msh_ts);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.alarm_ts)) {
                this.alarm_ts = data().deepCopy(fields()[1].schema(), other.alarm_ts);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.source)) {
                this.source = data().deepCopy(fields()[2].schema(), other.source);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.unit)) {
                this.unit = data().deepCopy(fields()[3].schema(), other.unit);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.bed)) {
                this.bed = data().deepCopy(fields()[4].schema(), other.bed);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.channel)) {
                this.channel = data().deepCopy(fields()[5].schema(), other.channel);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.text)) {
                this.text = data().deepCopy(fields()[6].schema(), other.text);
                fieldSetFlags()[6] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing ObxAvroModel instance
         * @param other The existing instance to copy.
         */
        private Builder(com.shane.ObxAvroModel other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.msh_ts)) {
                this.msh_ts = data().deepCopy(fields()[0].schema(), other.msh_ts);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.alarm_ts)) {
                this.alarm_ts = data().deepCopy(fields()[1].schema(), other.alarm_ts);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.source)) {
                this.source = data().deepCopy(fields()[2].schema(), other.source);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.unit)) {
                this.unit = data().deepCopy(fields()[3].schema(), other.unit);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.bed)) {
                this.bed = data().deepCopy(fields()[4].schema(), other.bed);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.channel)) {
                this.channel = data().deepCopy(fields()[5].schema(), other.channel);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.text)) {
                this.text = data().deepCopy(fields()[6].schema(), other.text);
                fieldSetFlags()[6] = true;
            }
        }

        /**
         * Gets the value of the 'msh_ts' field.
         * @return The value.
         */
        public java.lang.Long getMshTs() {
            return msh_ts;
        }

        /**
         * Sets the value of the 'msh_ts' field.
         * @param value The value of 'msh_ts'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setMshTs(long value) {
            validate(fields()[0], value);
            this.msh_ts = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'msh_ts' field has been set.
         * @return True if the 'msh_ts' field has been set, false otherwise.
         */
        public boolean hasMshTs() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'msh_ts' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearMshTs() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'alarm_ts' field.
         * @return The value.
         */
        public java.lang.Long getAlarmTs() {
            return alarm_ts;
        }

        /**
         * Sets the value of the 'alarm_ts' field.
         * @param value The value of 'alarm_ts'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setAlarmTs(long value) {
            validate(fields()[1], value);
            this.alarm_ts = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'alarm_ts' field has been set.
         * @return True if the 'alarm_ts' field has been set, false otherwise.
         */
        public boolean hasAlarmTs() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'alarm_ts' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearAlarmTs() {
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'source' field.
         * @return The value.
         */
        public java.lang.CharSequence getSource() {
            return source;
        }

        /**
         * Sets the value of the 'source' field.
         * @param value The value of 'source'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setSource(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.source = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'source' field has been set.
         * @return True if the 'source' field has been set, false otherwise.
         */
        public boolean hasSource() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'source' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearSource() {
            source = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'unit' field.
         * @return The value.
         */
        public java.lang.CharSequence getUnit() {
            return unit;
        }

        /**
         * Sets the value of the 'unit' field.
         * @param value The value of 'unit'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setUnit(java.lang.CharSequence value) {
            validate(fields()[3], value);
            this.unit = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'unit' field has been set.
         * @return True if the 'unit' field has been set, false otherwise.
         */
        public boolean hasUnit() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'unit' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearUnit() {
            unit = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'bed' field.
         * @return The value.
         */
        public java.lang.CharSequence getBed() {
            return bed;
        }

        /**
         * Sets the value of the 'bed' field.
         * @param value The value of 'bed'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setBed(java.lang.CharSequence value) {
            validate(fields()[4], value);
            this.bed = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'bed' field has been set.
         * @return True if the 'bed' field has been set, false otherwise.
         */
        public boolean hasBed() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'bed' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearBed() {
            bed = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'channel' field.
         * @return The value.
         */
        public java.lang.CharSequence getChannel() {
            return channel;
        }

        /**
         * Sets the value of the 'channel' field.
         * @param value The value of 'channel'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setChannel(java.lang.CharSequence value) {
            validate(fields()[5], value);
            this.channel = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'channel' field has been set.
         * @return True if the 'channel' field has been set, false otherwise.
         */
        public boolean hasChannel() {
            return fieldSetFlags()[5];
        }


        /**
         * Clears the value of the 'channel' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearChannel() {
            channel = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'text' field.
         * @return The value.
         */
        public java.lang.CharSequence getText() {
            return text;
        }

        /**
         * Sets the value of the 'text' field.
         * @param value The value of 'text'.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder setText(java.lang.CharSequence value) {
            validate(fields()[6], value);
            this.text = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'text' field has been set.
         * @return True if the 'text' field has been set, false otherwise.
         */
        public boolean hasText() {
            return fieldSetFlags()[6];
        }


        /**
         * Clears the value of the 'text' field.
         * @return This builder.
         */
        public com.shane.ObxAvroModel.Builder clearText() {
            text = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        @Override
        public ObxAvroModel build() {
            try {
                ObxAvroModel record = new ObxAvroModel();
                record.msh_ts = fieldSetFlags()[0] ? this.msh_ts : (java.lang.Long) defaultValue(fields()[0]);
                record.alarm_ts = fieldSetFlags()[1] ? this.alarm_ts : (java.lang.Long) defaultValue(fields()[1]);
                record.source = fieldSetFlags()[2] ? this.source : (java.lang.CharSequence) defaultValue(fields()[2]);
                record.unit = fieldSetFlags()[3] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[3]);
                record.bed = fieldSetFlags()[4] ? this.bed : (java.lang.CharSequence) defaultValue(fields()[4]);
                record.channel = fieldSetFlags()[5] ? this.channel : (java.lang.CharSequence) defaultValue(fields()[5]);
                record.text = fieldSetFlags()[6] ? this.text : (java.lang.CharSequence) defaultValue(fields()[6]);
                return record;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    private static final org.apache.avro.io.DatumWriter
            WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

    @Override public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    private static final org.apache.avro.io.DatumReader
            READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

    @Override public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

}
